---

- hosts: all
  pre_tasks:
    - name: Pre-run | Set the default shell to PowerShell
      win_regedit:
        path: HKLM:\SOFTWARE\OpenSSH
        name: DefaultShell
        data: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
        type: string
        state: present

    - name: Pre-run | Check for updates
      win_updates:
        state: searched

    - name: Pre-run | Install updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
        blacklist:
          - KB5022729
        reboot: yes
      register: update_result
      until: update_result.found_update_count == 0

- hosts: all
  roles:
    - base

- hosts: all
  vars_files:
    - roles/base/vars/main.yml
  tasks:
    - name: Post-cleanup | Temp files
      block:
        - name: Clean up all temporary files
          win_shell: |
            Remove-Item "{{ ansible_env.TEMP }}\*" -Recurse -Force
            Remove-Item "{{ ansible_env.SystemRoot }}\Temp\*" -Recurse -Force
            Remove-Item '%UserProfile%\AppData\Local\NuGet\Cache\*' -Recurse -Force
            $true
          register: cleanup_task
      rescue:
        - name: "{{ cleanup_task.msg }}"
          ansible.builtin.debug:
            msg: >
              "Some cache files are still in use. You may need to reboot your machine to resolve the error"

    - name: Telegram | Send completion alert
      include_tasks: roles/base/tasks/alerts/completion_alert.yml
      when:
        - task_failed is not defined

    - name: Telegram | Send failure alert
      include_tasks: roles/base/tasks/alerts/failure_alert.yml
      when:
        - task_failed is defined
        - task_failed == true
