---

- name: System setup | Power plan | Unlock Power Plans
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Power
    name: CsEnabled
    data: 0
    type: dword

- name: System setup | Power plan | Set power plan to {{ power_plan }}
  vars:
    plans:
      high_performance: "e9a42b02-d5df-448d-aa00-03f14749eb61"
      balanced: "381b4222-f694-41f0-9685-ff5bb260df2e"
      power_saver: "a1841308-3541-4fab-bc81-f71556f20b4a"
  win_power_plan:
    guid: "{{ plans[power_plan] | default(balanced) }}"
  ignore_errors: true
